//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    [MetadataType(typeof(AboutMetadata))]
    public partial class About
    {
    }
    public partial class AboutMetadata
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [AllowHtml]
        [Display(Name = "About Us")]
        [DataType(DataType.MultilineText)]
        public string AboutUs { get; set; }

        [Required]
        [AllowHtml]
        [Display(Name = "Vision")]
        [DataType(DataType.MultilineText)]
        public string Vision { get; set; }

        [Required]
        [AllowHtml]
        [Display(Name = "Mission")]
        [DataType(DataType.MultilineText)]
        public string Mission { get; set; }

        [Required]
        [AllowHtml]
        [Display(Name = "Values")]
        [DataType(DataType.MultilineText)]
        public string Values { get; set; }

        [Required]
        [AllowHtml]
        [Display(Name = "Core Business")]
        [DataType(DataType.MultilineText)]
        public string CoreBusiness { get; set; }

        [Required]
        [AllowHtml]
        [Display(Name = "Experience")]
        [DataType(DataType.MultilineText)]
        public string Experience { get; set; }

        [Required]
        [AllowHtml]
        [Display(Name = "Expertise")]
        [DataType(DataType.MultilineText)]
        public string Expertise { get; set; }

    }
}

