//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    [MetadataType(typeof(ContactUsMetadata))]
    public partial class ContactUs
    {
    }
    public class ContactUsMetadata
    {
        [Key]
        public int Id { get; set; }
        [Required, Display(Name ="Address1"), DataType(DataType.Text)]
        public string Address1 { get; set; }
        [Required, Display(Name = "Address2"), DataType(DataType.Text)]
        public string Address2 { get; set; }
        [Required, Display(Name = "Telephone No."), DataType(DataType.Text)]
        public string Phone { get; set; }
        [Required, Display(Name = "Fax No."), DataType(DataType.Text)]
        public string Fax { get; set; }
        [Required, Display(Name = "Email Address"), DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required, Display(Name = "Facebook Link"), DataType(DataType.Url)]
        public string Facebook { get; set; }
        [Required, Display(Name = "Twitter Link"), DataType(DataType.Url)]
        public string Twitter { get; set; }
        [Required, Display(Name = "LinkedIn Link"), DataType(DataType.Url)]
        public string LinkedIn { get; set; }
        public bool Active { get; set; }

    }
}

