//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    [MetadataType(typeof(EducationMetadata))]
    public partial class Education
    {
    }
    public class EducationMetadata
    {
        [Key]
        public int Id { get; set; }
        [Display(Name ="Is Highest?")]
        public bool Highest { get; set; }
        [Required, Display(Name = "Educational Institute"), DataType(DataType.Text)]
        public string EducationalInstitution { get; set; }
        [Required, Display(Name = "Discipline"), DataType(DataType.Text)]
        public string Discipline { get; set; }
        [Required, Display(Name = "Start Date"), DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime StartDate { get; set; }
        [Required, Display(Name = "End Date"), DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime EndDate { get; set; }
        [Required, Display(Name = "Education Level")]
        public string EducationLevel { get; set; }
        [Required, Display(Name = "Country")]
        public string Country { get; set; }
        [Display(Name = "Profile ID")]
        public int PersonalInfoId { get; set; }

    }
}

