//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    [MetadataType(typeof(HomeMetadata))]
    public partial class Home
    {
    }
    public partial class HomeMetadata
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [AllowHtml]
        [Display(Name = "Image Name")]
        [DataType(DataType.Text)]
        public string Name { get; set; }

        [Display(Name = "Image File")]
        [DataType(DataType.Upload)]
        public HttpPostedFileBase Image { get; set; }

        [Required]
        [AllowHtml]
        [Display(Name = "Description")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Active")]
        public bool Active { get; set; }

    }
}

