//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    [MetadataType(typeof(IsoCertificateMetadata))]
    public partial class IsoCertificate
    {
    }
    public class IsoCertificateMetadata
    {
        [Key]
        public int Id { get; set; }
        [Display(Name ="Title"), Required, DataType(DataType.Text)]
        public string Title { get; set; }
        [Display(Name = "Certificate Image"), Required, DataType(DataType.Upload)]
        public HttpPostedFileBase Document { get; set; }
        public string Description { get; set; }
        public int QHSEId { get; set; }

    }
}

