//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    [MetadataType(typeof(JobMetadata))]
    public partial class Job
    {
    }
    public class JobMetadata
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Job Title")]
        [DataType(DataType.Text)]
        public string JobTitle { get; set; }
        [Required]
        [AllowHtml]
        [Display(Name = "Job Details")]
        [DataType(DataType.MultilineText)]
        public HttpPostedFileBase JobDetails { get; set; }
        [Required]
        [Display(Name = "Job Type")]
        public string JobType { get; set; }

    }
}

