//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(JobApplicationMetadata))]
    public partial class JobApplication
    {
    }
    public class JobApplicationMetadata
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Apply Date")]
        [DataType(DataType.DateTime)]
        public System.DateTime ApplyDate { get; set; }
        [Required]
        [Display(Name = "Profile")]
        public int ProfileId { get; set; }
        [Required]
        [Display(Name = "Job")]
        public int JobId { get; set; }
    }
}

