//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(PersonalInfoMetadata))]
    public partial class PersonalInfo
    {
    }
    public class PersonalInfoMetadata
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Full Name")]
        [DataType(DataType.Text)]
        public string FullName { get; set; }
        [Required]
        [Display(Name = "Email Address")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [Display(Name = "Date Of Birth")]
        [DataType(DataType.Date)]
        public string DateOfBirth { get; set; }
        [Required]
        [Display(Name = "Nationality")]
        [DataType(DataType.Text)]
        public string Nationality { get; set; }
        [Required]
        [Display(Name = "Mobile No.")]
        [DataType(DataType.Text)]
        public string Phone1 { get; set; }

        [Display(Name = "Mobile No(Optional)")]
        [DataType(DataType.Text)]
        public string Phone2 { get; set; }
        [Required, Display(Name = "Gender")]
        [DataType(DataType.Text)]
        public string Gender { get; set; }


    }
}

