//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    [MetadataType(typeof(ProjectMetadata))]
    public partial class Project
    {
    }
    public partial class ProjectMetadata
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Project Name")]
        [DataType(DataType.Text)]
        public string ProjectTitle { get; set; }
        [Required]
        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        public string StartDate { get; set; }

        [Required]
        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        public string EndDate { get; set; }
        [Required]
        [Display(Name = "Client")]
        [DataType(DataType.Text)]
        public string Client { get; set; }
        [Required]
        [Display(Name = "Client Logo")]
        [DataType(DataType.Upload)]
        public HttpPostedFileBase ClientLogo { get; set; }
        [Required]
        [Display(Name = "Project Image")]
        [DataType(DataType.Upload)]
        public HttpPostedFileBase Image { get; set; }
        [Required]
        [Display(Name = "Description")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    }
}

