//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    [MetadataType(typeof(ServiceMetadata))]
    public partial class Service
    {
    }
    public class ServiceMetadata
    {
        public int Id { get; set; }
        [Required]
        [AllowHtml]
        [Display(Name = "Service Header")]
        [DataType(DataType.MultilineText)]
        public string ServiceHead { get; set; }
        [Required]
        [AllowHtml]
        [Display(Name = "Service Footer")]
        [DataType(DataType.MultilineText)]
        public string ServiceFoot { get; set; }

    }
}

