//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    [MetadataType(typeof(WorkExperienceMetadata))]
    public partial class WorkExperience
    {
    }
    public class WorkExperienceMetadata
    {
        [Key]
        public int Id { get; set; }
        [Required, Display(Name ="Employer"), DataType(DataType.Text)]
        public string Employer { get; set; }
        [Required, Display(Name = "Start Date"), DataType(DataType.Date)]
        public System.DateTime StartDate { get; set; }
        [Required, Display(Name = "End Date"), DataType(DataType.Date)]
        public System.DateTime EndDate { get; set; }
        [Required, Display(Name = "Job Title"), DataType(DataType.Text)]
        public string JobTitle { get; set; }
        [Required, Display(Name = "Profile ID")]
        public int PersonalInfoId { get; set; }

    }
}

