//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int Id { get; set; }
        public string AboutUs { get; set; }
        public string Vision { get; set; }
        public string Mission { get; set; }
        public string Values { get; set; }
        public string CoreBusiness { get; set; }
        public string Experience { get; set; }
        public string Expertise { get; set; }
    }
}
