//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Education()
        {
            this.Highest = false;
        }
    
        public int Id { get; set; }
        public string EducationalInstitution { get; set; }
        public string Discipline { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Highest { get; set; }
        public int PersonalInfoId { get; set; }
        public string EducationLevel { get; set; }
        public string Country { get; set; }
    
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
