//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QHSE
    {
        public int Id { get; set; }
        public string Vision { get; set; }
        public string Mission { get; set; }
        public string QhsePolicy { get; set; }
        public string QhsePolicyAr { get; set; }
        public string QhseIMS { get; set; }
        public string Hse { get; set; }
        public string IsoCertificates { get; set; }
    }
}
