//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDetails
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int ServiceId { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
