//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centroid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkExperience
    {
        public int Id { get; set; }
        public string Employer { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string JobTitle { get; set; }
        public int PersonalInfoId { get; set; }
    
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
